chore: Ensure commit message file always exist #3

diff --git a/infra/git/hooks/commit-msg b/infra/git/hooks/commit-msg
--- a/infra/git/hooks/commit-msg
+++ b/infra/git/hooks/commit-msg
@@ -10,6 +10,10 @@ if [[ $branch_name =~ ^[a-z]+/[0-9]+$ ]]; then
 
   # Get the current commit message
   commit_msg_file=$1
+  if [ ! -f "$commit_msg_file" ] || [ ! -r "$commit_msg_file" ]; then
+    echo "Error: Cannot read commit message file"
+    exit 1
+  fi
   commit_msg=$(cat "$commit_msg_file")
 
   # Check if the commit message already mentions the issue number.
